name: "Coverage"
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: windows-2022
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        shell: pwsh
        run: |
          pip install uv
      - name: Install MonitorBoss
        shell: pwsh
        run: |
          uv lock --upgrade
          uv sync
      - name: Test MonitorBoss
        shell: pwsh
        run: |
          uv run pytest
      - name: Check MonitorBoss code coverage
        shell: pwsh
        run: |
          uv run pytest --cov=. --cov-report term-missing .
